######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 20:37:54 2016
######################################################################

TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = .

#QMAKE_CXXFLAGS += -std=c++0x

include(../../../netlizard-game.pri)

QT -= core gui
CONFIG -= qt
CONFIG += debug_and_release x11
OBJECTS_DIR = ../.opengl

# Input
harmattan_opengles2{
HEADERS += gles2.0/opengl/opengl2.h \
opengl2_math.h \
opengl2_port.h \
opengl2_def.h

SOURCES += opengl2.c \
opengl2_attrib.c \
opengl2_math.c \
opengl2_matrix.c \
opengl2_program.c \
opengl2_shaderprogram.c \
opengl2_transform.c \
main.c
}
