######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 20:37:54 2016
######################################################################

TEMPLATE = app
TARGET = test

include(../netlizard-game.pri)

DEPENDPATH += . .. $$BUILD_DIR/renderer $$BUILD_DIR/libs
INCLUDEPATH += . .. $$BUILD_DIR/renderer $$BUILD_DIR/libs

LIBS += -lSOIL -lglk -lopengl
PRE_TARGETDEPS += $$DESTDIR/libglk.so $$DESTDIR/libSOIL.so $$DESTDIR/libopengl.so

CONFIG += x11
LIBS += -lSDL -lSDL_mixer

# Input

SOURCES += main.c
