#############################################################################
# Makefile for building: netlizard-game
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 4? 14 19:25:41 2019
# Project:  netlizard-game.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile netlizard-game.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-renderer \
		sub-netlizard \
		sub-libs \
		sub-src \
		sub-test

renderer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) renderer/ || $(MKDIR) renderer/ 
	cd renderer/ && $(QMAKE) /home/user/class/netlizard-game/renderer/renderer.pro -o $(MAKEFILE)
sub-renderer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) renderer/ || $(MKDIR) renderer/ 
	cd renderer/ && $(QMAKE) /home/user/class/netlizard-game/renderer/renderer.pro -o $(MAKEFILE)
sub-renderer: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE)
sub-renderer-make_default-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) 
sub-renderer-make_default: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) 
sub-renderer-make_first-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) first
sub-renderer-make_first: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) first
sub-renderer-all-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) all
sub-renderer-all: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) all
sub-renderer-clean-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) clean
sub-renderer-clean: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) clean
sub-renderer-distclean-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-renderer-distclean: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-renderer-install_subtargets-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) install
sub-renderer-install_subtargets: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) install
sub-renderer-uninstall_subtargets-ordered: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-renderer-uninstall_subtargets: renderer/$(MAKEFILE) FORCE
	cd renderer/ && $(MAKE) -f $(MAKEFILE) uninstall
netlizard/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) netlizard/ || $(MKDIR) netlizard/ 
	cd netlizard/ && $(QMAKE) /home/user/class/netlizard-game/netlizard/netlizard.pro -o $(MAKEFILE)
sub-netlizard-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) netlizard/ || $(MKDIR) netlizard/ 
	cd netlizard/ && $(QMAKE) /home/user/class/netlizard-game/netlizard/netlizard.pro -o $(MAKEFILE)
sub-netlizard: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE)
sub-netlizard-make_default-ordered: netlizard/$(MAKEFILE) sub-renderer-make_default-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) 
sub-netlizard-make_default: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) 
sub-netlizard-make_first-ordered: netlizard/$(MAKEFILE) sub-renderer-make_first-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) first
sub-netlizard-make_first: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) first
sub-netlizard-all-ordered: netlizard/$(MAKEFILE) sub-renderer-all-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) all
sub-netlizard-all: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) all
sub-netlizard-clean-ordered: netlizard/$(MAKEFILE) sub-renderer-clean-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) clean
sub-netlizard-clean: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) clean
sub-netlizard-distclean-ordered: netlizard/$(MAKEFILE) sub-renderer-distclean-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) distclean
sub-netlizard-distclean: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) distclean
sub-netlizard-install_subtargets-ordered: netlizard/$(MAKEFILE) sub-renderer-install_subtargets-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) install
sub-netlizard-install_subtargets: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) install
sub-netlizard-uninstall_subtargets-ordered: netlizard/$(MAKEFILE) sub-renderer-uninstall_subtargets-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-netlizard-uninstall_subtargets: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) uninstall
libs/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /home/user/class/netlizard-game/libs/libs.pro -o $(MAKEFILE)
sub-libs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /home/user/class/netlizard-game/libs/libs.pro -o $(MAKEFILE)
sub-libs: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE)
sub-libs-make_default-ordered: libs/$(MAKEFILE) sub-netlizard-make_default-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_default: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_first-ordered: libs/$(MAKEFILE) sub-netlizard-make_first-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) first
sub-libs-make_first: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) first
sub-libs-all-ordered: libs/$(MAKEFILE) sub-netlizard-all-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) all
sub-libs-all: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) all
sub-libs-clean-ordered: libs/$(MAKEFILE) sub-netlizard-clean-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-clean: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-distclean-ordered: libs/$(MAKEFILE) sub-netlizard-distclean-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-distclean: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-install_subtargets-ordered: libs/$(MAKEFILE) sub-netlizard-install_subtargets-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) install
sub-libs-install_subtargets: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) install
sub-libs-uninstall_subtargets-ordered: libs/$(MAKEFILE) sub-netlizard-uninstall_subtargets-ordered  FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libs-uninstall_subtargets: libs/$(MAKEFILE) FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE) uninstall
src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/user/class/netlizard-game/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/user/class/netlizard-game/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) sub-libs-make_default-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) sub-libs-make_first-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) sub-libs-all-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) sub-libs-clean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) sub-libs-distclean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) sub-libs-install_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) sub-libs-uninstall_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
test/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) test/ || $(MKDIR) test/ 
	cd test/ && $(QMAKE) /home/user/class/netlizard-game/test/test.pro -o $(MAKEFILE)
sub-test-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) test/ || $(MKDIR) test/ 
	cd test/ && $(QMAKE) /home/user/class/netlizard-game/test/test.pro -o $(MAKEFILE)
sub-test: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE)
sub-test-make_default-ordered: test/$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) 
sub-test-make_default: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) 
sub-test-make_first-ordered: test/$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) first
sub-test-make_first: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) first
sub-test-all-ordered: test/$(MAKEFILE) sub-src-all-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) all
sub-test-all: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) all
sub-test-clean-ordered: test/$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-clean: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-distclean-ordered: test/$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-distclean: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-install_subtargets-ordered: test/$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) install
sub-test-install_subtargets: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) install
sub-test-uninstall_subtargets-ordered: test/$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-test-uninstall_subtargets: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: netlizard-game.pro  /usr/share/qt4/mkspecs/linux-g++-maemo/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		netlizard-game.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/debug_and_release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile netlizard-game.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
netlizard-game.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/debug_and_release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile netlizard-game.pro

qmake_all: sub-renderer-qmake_all sub-netlizard-qmake_all sub-libs-qmake_all sub-src-qmake_all sub-test-qmake_all FORCE

make_default: sub-renderer-make_default-ordered sub-netlizard-make_default-ordered sub-libs-make_default-ordered sub-src-make_default-ordered sub-test-make_default-ordered FORCE
make_first: sub-renderer-make_first-ordered sub-netlizard-make_first-ordered sub-libs-make_first-ordered sub-src-make_first-ordered sub-test-make_first-ordered FORCE
all: sub-renderer-all-ordered sub-netlizard-all-ordered sub-libs-all-ordered sub-src-all-ordered sub-test-all-ordered FORCE
clean: sub-renderer-clean-ordered sub-netlizard-clean-ordered sub-libs-clean-ordered sub-src-clean-ordered sub-test-clean-ordered FORCE
distclean: sub-renderer-distclean-ordered sub-netlizard-distclean-ordered sub-libs-distclean-ordered sub-src-distclean-ordered sub-test-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-renderer-install_subtargets-ordered sub-netlizard-install_subtargets-ordered sub-libs-install_subtargets-ordered sub-src-install_subtargets-ordered sub-test-install_subtargets-ordered FORCE
uninstall_subtargets: sub-renderer-uninstall_subtargets-ordered sub-netlizard-uninstall_subtargets-ordered sub-libs-uninstall_subtargets-ordered sub-src-uninstall_subtargets-ordered sub-test-uninstall_subtargets-ordered FORCE

sub-renderer-sub_Debug_ordered: renderer/$(MAKEFILE)
	cd renderer/ && $(MAKE) debug
sub-netlizard-sub_Debug_ordered: netlizard/$(MAKEFILE) sub-renderer-sub_Debug_ordered 
	cd netlizard/ && $(MAKE) debug
sub-libs-sub_Debug_ordered: libs/$(MAKEFILE) sub-netlizard-sub_Debug_ordered 
	cd libs/ && $(MAKE) debug
sub-src-sub_Debug_ordered: src/$(MAKEFILE) sub-libs-sub_Debug_ordered 
	cd src/ && $(MAKE) debug
sub-test-sub_Debug_ordered: test/$(MAKEFILE) sub-src-sub_Debug_ordered 
	cd test/ && $(MAKE) debug
debug: sub-renderer-sub_Debug_ordered sub-netlizard-sub_Debug_ordered sub-libs-sub_Debug_ordered sub-src-sub_Debug_ordered sub-test-sub_Debug_ordered

sub-renderer-sub_Release_ordered: renderer/$(MAKEFILE)
	cd renderer/ && $(MAKE) release
sub-netlizard-sub_Release_ordered: netlizard/$(MAKEFILE) sub-renderer-sub_Release_ordered 
	cd netlizard/ && $(MAKE) release
sub-libs-sub_Release_ordered: libs/$(MAKEFILE) sub-netlizard-sub_Release_ordered 
	cd libs/ && $(MAKE) release
sub-src-sub_Release_ordered: src/$(MAKEFILE) sub-libs-sub_Release_ordered 
	cd src/ && $(MAKE) release
sub-test-sub_Release_ordered: test/$(MAKEFILE) sub-src-sub_Release_ordered 
	cd test/ && $(MAKE) release
release: sub-renderer-sub_Release_ordered sub-netlizard-sub_Release_ordered sub-libs-sub_Release_ordered sub-src-sub_Release_ordered sub-test-sub_Release_ordered

sub-renderer-check_ordered: renderer/$(MAKEFILE)
	cd renderer/ && $(MAKE) check
sub-netlizard-check_ordered: netlizard/$(MAKEFILE) sub-renderer-check_ordered 
	cd netlizard/ && $(MAKE) check
sub-libs-check_ordered: libs/$(MAKEFILE) sub-netlizard-check_ordered 
	cd libs/ && $(MAKE) check
sub-src-check_ordered: src/$(MAKEFILE) sub-libs-check_ordered 
	cd src/ && $(MAKE) check
sub-test-check_ordered: test/$(MAKEFILE) sub-src-check_ordered 
	cd test/ && $(MAKE) check
check: sub-renderer-check_ordered sub-netlizard-check_ordered sub-libs-check_ordered sub-src-check_ordered sub-test-check_ordered
install_itemrsc: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/resource $(INSTALL_ROOT)/usr/share/netlizard-game/./


uninstall_itemrsc:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./resource
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./ 


install_itemct3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemspecnaz3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/specnaz3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemspecnaz3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/specnaz3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemct3dep2: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3dep2 $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3dep2:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3dep2
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemegypt3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/egypt3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemegypt3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/egypt3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemclone3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/clone3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemclone3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/clone3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemct3dep3: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3dep3 $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3dep3:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3dep3
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemre3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/re3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemre3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/re3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_icon: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) /home/user/class/netlizard-game/netlizard-game_80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/netlizard-game_80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/user/class/netlizard-game/netlizard-game_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/netlizard-game_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install: install_subtargets install_itemrsc install_itemct3d install_itemspecnaz3d install_itemct3dep2 install_itemegypt3d install_itemclone3d install_itemct3dep3 install_itemre3d install_icon install_desktopfile  FORCE

uninstall: uninstall_itemrsc uninstall_itemct3d uninstall_itemspecnaz3d uninstall_itemct3dep2 uninstall_itemegypt3d uninstall_itemclone3d uninstall_itemct3dep3 uninstall_itemre3d uninstall_icon uninstall_desktopfile  uninstall_subtargets FORCE

FORCE:

