#############################################################################
# Makefile for building: netlizard-game
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 7? 20 12:48:11 2018
# Project:  netlizard-game.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile netlizard-game.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-opengl \
		sub-SOIL \
		sub-glk \
		sub-netlizard \
		sub-math3d \
		sub-lolking \
		sub-bio \
		sub-csol \
		sub-src \
		sub-testapp

opengl/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) opengl/ || $(MKDIR) opengl/ 
	cd opengl/ && $(QMAKE) /home/user/class/netlizard-game/opengl/opengl.pro -o $(MAKEFILE)
sub-opengl-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) opengl/ || $(MKDIR) opengl/ 
	cd opengl/ && $(QMAKE) /home/user/class/netlizard-game/opengl/opengl.pro -o $(MAKEFILE)
sub-opengl: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE)
sub-opengl-make_default-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) 
sub-opengl-make_default: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) 
sub-opengl-make_first-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) first
sub-opengl-make_first: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) first
sub-opengl-all-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) all
sub-opengl-all: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) all
sub-opengl-clean-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) clean
sub-opengl-clean: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) clean
sub-opengl-distclean-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) distclean
sub-opengl-distclean: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) distclean
sub-opengl-install_subtargets-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) install
sub-opengl-install_subtargets: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) install
sub-opengl-uninstall_subtargets-ordered: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-opengl-uninstall_subtargets: opengl/$(MAKEFILE) FORCE
	cd opengl/ && $(MAKE) -f $(MAKEFILE) uninstall
SOIL/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SOIL/ || $(MKDIR) SOIL/ 
	cd SOIL/ && $(QMAKE) /home/user/class/netlizard-game/SOIL/SOIL.pro -o $(MAKEFILE)
sub-SOIL-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SOIL/ || $(MKDIR) SOIL/ 
	cd SOIL/ && $(QMAKE) /home/user/class/netlizard-game/SOIL/SOIL.pro -o $(MAKEFILE)
sub-SOIL: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE)
sub-SOIL-make_default-ordered: SOIL/$(MAKEFILE) sub-opengl-make_default-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) 
sub-SOIL-make_default: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) 
sub-SOIL-make_first-ordered: SOIL/$(MAKEFILE) sub-opengl-make_first-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) first
sub-SOIL-make_first: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) first
sub-SOIL-all-ordered: SOIL/$(MAKEFILE) sub-opengl-all-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) all
sub-SOIL-all: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) all
sub-SOIL-clean-ordered: SOIL/$(MAKEFILE) sub-opengl-clean-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) clean
sub-SOIL-clean: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) clean
sub-SOIL-distclean-ordered: SOIL/$(MAKEFILE) sub-opengl-distclean-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SOIL-distclean: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) distclean
sub-SOIL-install_subtargets-ordered: SOIL/$(MAKEFILE) sub-opengl-install_subtargets-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) install
sub-SOIL-install_subtargets: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) install
sub-SOIL-uninstall_subtargets-ordered: SOIL/$(MAKEFILE) sub-opengl-uninstall_subtargets-ordered  FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-SOIL-uninstall_subtargets: SOIL/$(MAKEFILE) FORCE
	cd SOIL/ && $(MAKE) -f $(MAKEFILE) uninstall
glk/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) glk/ || $(MKDIR) glk/ 
	cd glk/ && $(QMAKE) /home/user/class/netlizard-game/glk/glk.pro -o $(MAKEFILE)
sub-glk-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) glk/ || $(MKDIR) glk/ 
	cd glk/ && $(QMAKE) /home/user/class/netlizard-game/glk/glk.pro -o $(MAKEFILE)
sub-glk: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE)
sub-glk-make_default-ordered: glk/$(MAKEFILE) sub-SOIL-make_default-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) 
sub-glk-make_default: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) 
sub-glk-make_first-ordered: glk/$(MAKEFILE) sub-SOIL-make_first-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) first
sub-glk-make_first: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) first
sub-glk-all-ordered: glk/$(MAKEFILE) sub-SOIL-all-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) all
sub-glk-all: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) all
sub-glk-clean-ordered: glk/$(MAKEFILE) sub-SOIL-clean-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) clean
sub-glk-clean: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) clean
sub-glk-distclean-ordered: glk/$(MAKEFILE) sub-SOIL-distclean-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) distclean
sub-glk-distclean: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) distclean
sub-glk-install_subtargets-ordered: glk/$(MAKEFILE) sub-SOIL-install_subtargets-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) install
sub-glk-install_subtargets: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) install
sub-glk-uninstall_subtargets-ordered: glk/$(MAKEFILE) sub-SOIL-uninstall_subtargets-ordered  FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-glk-uninstall_subtargets: glk/$(MAKEFILE) FORCE
	cd glk/ && $(MAKE) -f $(MAKEFILE) uninstall
netlizard/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) netlizard/ || $(MKDIR) netlizard/ 
	cd netlizard/ && $(QMAKE) /home/user/class/netlizard-game/netlizard/netlizard.pro -o $(MAKEFILE)
sub-netlizard-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) netlizard/ || $(MKDIR) netlizard/ 
	cd netlizard/ && $(QMAKE) /home/user/class/netlizard-game/netlizard/netlizard.pro -o $(MAKEFILE)
sub-netlizard: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE)
sub-netlizard-make_default-ordered: netlizard/$(MAKEFILE) sub-glk-make_default-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) 
sub-netlizard-make_default: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) 
sub-netlizard-make_first-ordered: netlizard/$(MAKEFILE) sub-glk-make_first-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) first
sub-netlizard-make_first: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) first
sub-netlizard-all-ordered: netlizard/$(MAKEFILE) sub-glk-all-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) all
sub-netlizard-all: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) all
sub-netlizard-clean-ordered: netlizard/$(MAKEFILE) sub-glk-clean-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) clean
sub-netlizard-clean: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) clean
sub-netlizard-distclean-ordered: netlizard/$(MAKEFILE) sub-glk-distclean-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) distclean
sub-netlizard-distclean: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) distclean
sub-netlizard-install_subtargets-ordered: netlizard/$(MAKEFILE) sub-glk-install_subtargets-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) install
sub-netlizard-install_subtargets: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) install
sub-netlizard-uninstall_subtargets-ordered: netlizard/$(MAKEFILE) sub-glk-uninstall_subtargets-ordered  FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-netlizard-uninstall_subtargets: netlizard/$(MAKEFILE) FORCE
	cd netlizard/ && $(MAKE) -f $(MAKEFILE) uninstall
math3d/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) math3d/ || $(MKDIR) math3d/ 
	cd math3d/ && $(QMAKE) /home/user/class/netlizard-game/math3d/math3d.pro -o $(MAKEFILE)
sub-math3d-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) math3d/ || $(MKDIR) math3d/ 
	cd math3d/ && $(QMAKE) /home/user/class/netlizard-game/math3d/math3d.pro -o $(MAKEFILE)
sub-math3d: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE)
sub-math3d-make_default-ordered: math3d/$(MAKEFILE) sub-netlizard-make_default-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) 
sub-math3d-make_default: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) 
sub-math3d-make_first-ordered: math3d/$(MAKEFILE) sub-netlizard-make_first-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) first
sub-math3d-make_first: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) first
sub-math3d-all-ordered: math3d/$(MAKEFILE) sub-netlizard-all-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) all
sub-math3d-all: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) all
sub-math3d-clean-ordered: math3d/$(MAKEFILE) sub-netlizard-clean-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) clean
sub-math3d-clean: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) clean
sub-math3d-distclean-ordered: math3d/$(MAKEFILE) sub-netlizard-distclean-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) distclean
sub-math3d-distclean: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) distclean
sub-math3d-install_subtargets-ordered: math3d/$(MAKEFILE) sub-netlizard-install_subtargets-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) install
sub-math3d-install_subtargets: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) install
sub-math3d-uninstall_subtargets-ordered: math3d/$(MAKEFILE) sub-netlizard-uninstall_subtargets-ordered  FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-math3d-uninstall_subtargets: math3d/$(MAKEFILE) FORCE
	cd math3d/ && $(MAKE) -f $(MAKEFILE) uninstall
lolking/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) lolking/ || $(MKDIR) lolking/ 
	cd lolking/ && $(QMAKE) /home/user/class/netlizard-game/lolking/lolking.pro -o $(MAKEFILE)
sub-lolking-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) lolking/ || $(MKDIR) lolking/ 
	cd lolking/ && $(QMAKE) /home/user/class/netlizard-game/lolking/lolking.pro -o $(MAKEFILE)
sub-lolking: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE)
sub-lolking-make_default-ordered: lolking/$(MAKEFILE) sub-math3d-make_default-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) 
sub-lolking-make_default: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) 
sub-lolking-make_first-ordered: lolking/$(MAKEFILE) sub-math3d-make_first-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) first
sub-lolking-make_first: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) first
sub-lolking-all-ordered: lolking/$(MAKEFILE) sub-math3d-all-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) all
sub-lolking-all: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) all
sub-lolking-clean-ordered: lolking/$(MAKEFILE) sub-math3d-clean-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) clean
sub-lolking-clean: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) clean
sub-lolking-distclean-ordered: lolking/$(MAKEFILE) sub-math3d-distclean-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lolking-distclean: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lolking-install_subtargets-ordered: lolking/$(MAKEFILE) sub-math3d-install_subtargets-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) install
sub-lolking-install_subtargets: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) install
sub-lolking-uninstall_subtargets-ordered: lolking/$(MAKEFILE) sub-math3d-uninstall_subtargets-ordered  FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-lolking-uninstall_subtargets: lolking/$(MAKEFILE) FORCE
	cd lolking/ && $(MAKE) -f $(MAKEFILE) uninstall
bio/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) bio/ || $(MKDIR) bio/ 
	cd bio/ && $(QMAKE) /home/user/class/netlizard-game/bio/bio.pro -o $(MAKEFILE)
sub-bio-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) bio/ || $(MKDIR) bio/ 
	cd bio/ && $(QMAKE) /home/user/class/netlizard-game/bio/bio.pro -o $(MAKEFILE)
sub-bio: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE)
sub-bio-make_default-ordered: bio/$(MAKEFILE) sub-lolking-make_default-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) 
sub-bio-make_default: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) 
sub-bio-make_first-ordered: bio/$(MAKEFILE) sub-lolking-make_first-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) first
sub-bio-make_first: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) first
sub-bio-all-ordered: bio/$(MAKEFILE) sub-lolking-all-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) all
sub-bio-all: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) all
sub-bio-clean-ordered: bio/$(MAKEFILE) sub-lolking-clean-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) clean
sub-bio-clean: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) clean
sub-bio-distclean-ordered: bio/$(MAKEFILE) sub-lolking-distclean-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) distclean
sub-bio-distclean: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) distclean
sub-bio-install_subtargets-ordered: bio/$(MAKEFILE) sub-lolking-install_subtargets-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) install
sub-bio-install_subtargets: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) install
sub-bio-uninstall_subtargets-ordered: bio/$(MAKEFILE) sub-lolking-uninstall_subtargets-ordered  FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-bio-uninstall_subtargets: bio/$(MAKEFILE) FORCE
	cd bio/ && $(MAKE) -f $(MAKEFILE) uninstall
csol/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) csol/ || $(MKDIR) csol/ 
	cd csol/ && $(QMAKE) /home/user/class/netlizard-game/csol/csol.pro -o $(MAKEFILE)
sub-csol-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) csol/ || $(MKDIR) csol/ 
	cd csol/ && $(QMAKE) /home/user/class/netlizard-game/csol/csol.pro -o $(MAKEFILE)
sub-csol: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE)
sub-csol-make_default-ordered: csol/$(MAKEFILE) sub-bio-make_default-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) 
sub-csol-make_default: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) 
sub-csol-make_first-ordered: csol/$(MAKEFILE) sub-bio-make_first-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) first
sub-csol-make_first: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) first
sub-csol-all-ordered: csol/$(MAKEFILE) sub-bio-all-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) all
sub-csol-all: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) all
sub-csol-clean-ordered: csol/$(MAKEFILE) sub-bio-clean-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) clean
sub-csol-clean: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) clean
sub-csol-distclean-ordered: csol/$(MAKEFILE) sub-bio-distclean-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) distclean
sub-csol-distclean: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) distclean
sub-csol-install_subtargets-ordered: csol/$(MAKEFILE) sub-bio-install_subtargets-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) install
sub-csol-install_subtargets: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) install
sub-csol-uninstall_subtargets-ordered: csol/$(MAKEFILE) sub-bio-uninstall_subtargets-ordered  FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-csol-uninstall_subtargets: csol/$(MAKEFILE) FORCE
	cd csol/ && $(MAKE) -f $(MAKEFILE) uninstall
src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/user/class/netlizard-game/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/user/class/netlizard-game/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) sub-csol-make_default-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) sub-csol-make_first-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) sub-csol-all-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) sub-csol-clean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) sub-csol-distclean-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) sub-csol-install_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) sub-csol-uninstall_subtargets-ordered  FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
testapp/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) testapp/ || $(MKDIR) testapp/ 
	cd testapp/ && $(QMAKE) /home/user/class/netlizard-game/testapp/testapp.pro -o $(MAKEFILE)
sub-testapp-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) testapp/ || $(MKDIR) testapp/ 
	cd testapp/ && $(QMAKE) /home/user/class/netlizard-game/testapp/testapp.pro -o $(MAKEFILE)
sub-testapp: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE)
sub-testapp-make_default-ordered: testapp/$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) 
sub-testapp-make_default: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) 
sub-testapp-make_first-ordered: testapp/$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) first
sub-testapp-make_first: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) first
sub-testapp-all-ordered: testapp/$(MAKEFILE) sub-src-all-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) all
sub-testapp-all: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) all
sub-testapp-clean-ordered: testapp/$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) clean
sub-testapp-clean: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) clean
sub-testapp-distclean-ordered: testapp/$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-testapp-distclean: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-testapp-install_subtargets-ordered: testapp/$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) install
sub-testapp-install_subtargets: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) install
sub-testapp-uninstall_subtargets-ordered: testapp/$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-testapp-uninstall_subtargets: testapp/$(MAKEFILE) FORCE
	cd testapp/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: netlizard-game.pro  /usr/share/qt4/mkspecs/linux-g++-maemo/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile netlizard-game.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile netlizard-game.pro

qmake_all: sub-opengl-qmake_all sub-SOIL-qmake_all sub-glk-qmake_all sub-netlizard-qmake_all sub-math3d-qmake_all sub-lolking-qmake_all sub-bio-qmake_all sub-csol-qmake_all sub-src-qmake_all sub-testapp-qmake_all FORCE

make_default: sub-opengl-make_default-ordered sub-SOIL-make_default-ordered sub-glk-make_default-ordered sub-netlizard-make_default-ordered sub-math3d-make_default-ordered sub-lolking-make_default-ordered sub-bio-make_default-ordered sub-csol-make_default-ordered sub-src-make_default-ordered sub-testapp-make_default-ordered FORCE
make_first: sub-opengl-make_first-ordered sub-SOIL-make_first-ordered sub-glk-make_first-ordered sub-netlizard-make_first-ordered sub-math3d-make_first-ordered sub-lolking-make_first-ordered sub-bio-make_first-ordered sub-csol-make_first-ordered sub-src-make_first-ordered sub-testapp-make_first-ordered FORCE
all: sub-opengl-all-ordered sub-SOIL-all-ordered sub-glk-all-ordered sub-netlizard-all-ordered sub-math3d-all-ordered sub-lolking-all-ordered sub-bio-all-ordered sub-csol-all-ordered sub-src-all-ordered sub-testapp-all-ordered FORCE
clean: sub-opengl-clean-ordered sub-SOIL-clean-ordered sub-glk-clean-ordered sub-netlizard-clean-ordered sub-math3d-clean-ordered sub-lolking-clean-ordered sub-bio-clean-ordered sub-csol-clean-ordered sub-src-clean-ordered sub-testapp-clean-ordered FORCE
distclean: sub-opengl-distclean-ordered sub-SOIL-distclean-ordered sub-glk-distclean-ordered sub-netlizard-distclean-ordered sub-math3d-distclean-ordered sub-lolking-distclean-ordered sub-bio-distclean-ordered sub-csol-distclean-ordered sub-src-distclean-ordered sub-testapp-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-opengl-install_subtargets-ordered sub-SOIL-install_subtargets-ordered sub-glk-install_subtargets-ordered sub-netlizard-install_subtargets-ordered sub-math3d-install_subtargets-ordered sub-lolking-install_subtargets-ordered sub-bio-install_subtargets-ordered sub-csol-install_subtargets-ordered sub-src-install_subtargets-ordered sub-testapp-install_subtargets-ordered FORCE
uninstall_subtargets: sub-opengl-uninstall_subtargets-ordered sub-SOIL-uninstall_subtargets-ordered sub-glk-uninstall_subtargets-ordered sub-netlizard-uninstall_subtargets-ordered sub-math3d-uninstall_subtargets-ordered sub-lolking-uninstall_subtargets-ordered sub-bio-uninstall_subtargets-ordered sub-csol-uninstall_subtargets-ordered sub-src-uninstall_subtargets-ordered sub-testapp-uninstall_subtargets-ordered FORCE

sub-opengl-check_ordered: opengl/$(MAKEFILE)
	cd opengl/ && $(MAKE) check
sub-SOIL-check_ordered: SOIL/$(MAKEFILE) sub-opengl-check_ordered 
	cd SOIL/ && $(MAKE) check
sub-glk-check_ordered: glk/$(MAKEFILE) sub-SOIL-check_ordered 
	cd glk/ && $(MAKE) check
sub-netlizard-check_ordered: netlizard/$(MAKEFILE) sub-glk-check_ordered 
	cd netlizard/ && $(MAKE) check
sub-math3d-check_ordered: math3d/$(MAKEFILE) sub-netlizard-check_ordered 
	cd math3d/ && $(MAKE) check
sub-lolking-check_ordered: lolking/$(MAKEFILE) sub-math3d-check_ordered 
	cd lolking/ && $(MAKE) check
sub-bio-check_ordered: bio/$(MAKEFILE) sub-lolking-check_ordered 
	cd bio/ && $(MAKE) check
sub-csol-check_ordered: csol/$(MAKEFILE) sub-bio-check_ordered 
	cd csol/ && $(MAKE) check
sub-src-check_ordered: src/$(MAKEFILE) sub-csol-check_ordered 
	cd src/ && $(MAKE) check
sub-testapp-check_ordered: testapp/$(MAKEFILE) sub-src-check_ordered 
	cd testapp/ && $(MAKE) check
check: sub-opengl-check_ordered sub-SOIL-check_ordered sub-glk-check_ordered sub-netlizard-check_ordered sub-math3d-check_ordered sub-lolking-check_ordered sub-bio-check_ordered sub-csol-check_ordered sub-src-check_ordered sub-testapp-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_itemrsc: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/resource $(INSTALL_ROOT)/usr/share/netlizard-game/./


uninstall_itemrsc:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./resource
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./ 


install_itemct3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemspecnaz3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/specnaz3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemspecnaz3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/specnaz3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemct3dep2: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3dep2 $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3dep2:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3dep2
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemegypt3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/egypt3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemegypt3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/egypt3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemclone3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/clone3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemclone3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/clone3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemct3dep3: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/ct3dep3 $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemct3dep3:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ct3dep3
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_itemre3d: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 
	-$(INSTALL_DIR) /home/user/class/netlizard-game/re3d $(INSTALL_ROOT)/usr/share/netlizard-game/./game/


uninstall_itemre3d:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/netlizard-game/./game/re3d
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/netlizard-game/./game/ 


install_icon: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) /home/user/class/netlizard-game/netlizard-game_80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/netlizard-game_80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/user/class/netlizard-game/netlizard-game_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/netlizard-game_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install: install_subtargets install_itemrsc install_itemct3d install_itemspecnaz3d install_itemct3dep2 install_itemegypt3d install_itemclone3d install_itemct3dep3 install_itemre3d install_icon install_desktopfile  FORCE

uninstall: uninstall_itemrsc uninstall_itemct3d uninstall_itemspecnaz3d uninstall_itemct3dep2 uninstall_itemegypt3d uninstall_itemclone3d uninstall_itemct3dep3 uninstall_itemre3d uninstall_icon uninstall_desktopfile  uninstall_subtargets FORCE

FORCE:

